export var SAUDI_STOCKS = {
  "2222": { name: "أرامكو", en: "Aramco", sector: "الطاقة" },
  "1120": { name: "الراجحي", en: "Al Rajhi", sector: "البنوك" },
  "1180": { name: "الأهلي", en: "SNB", sector: "البنوك" },
  "2010": { name: "سابك", en: "SABIC", sector: "المواد" },
  "7010": { name: "STC", en: "STC", sector: "الاتصالات" },
  "4030": { name: "البحري", en: "Bahri", sector: "النقل" },
  "4190": { name: "جرير", en: "Jarir", sector: "التجزئة" },
  "4200": { name: "الدريس", en: "Aldrees", sector: "الطاقة" },
  "2350": { name: "كيان", en: "Kayan", sector: "المواد" },
  "1010": { name: "الرياض", en: "Riyad Bank", sector: "البنوك" },
  "2280": { name: "المراعي", en: "Almarai", sector: "الأغذية" },
  "8010": { name: "التعاونية", en: "Tawuniya", sector: "التأمين" },
  "2060": { name: "التصنيع", en: "Tasnee", sector: "المواد" },
  "4260": { name: "بدجت", en: "Budget", sector: "النقل" },
  "1150": { name: "البنك الأول", en: "SAB", sector: "البنوك" },
  "2150": { name: "زين", en: "Zain KSA", sector: "الاتصالات" },
  "2050": { name: "صافولا", en: "Savola", sector: "الأغذية" },
  "3010": { name: "أسمنت العربية", en: "Arabian Cement", sector: "الأسمنت" },
  "2020": { name: "سابك للمغذيات", en: "SABIC Agri", sector: "المواد" },
};
